Vagrant.configure("2") do |config|
  config.vm.box = "dduportal/boot2docker"

  # Configure B2D to use consul dns settings
  config.vm.provision "shell", path: 'consul.sh'
  config.vm.provision "shell", path: 'shellinit.sh'
end
