Vagrant.configure("2") do |config|
  # config.vm.box = "cargonauts/boot2docker"
  config.vm.box = "dduportal/boot2docker"

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  # Configure B2D to use consul dns settings
  config.vm.provision "shell", path: 'consul.sh'
  config.vm.provision "shell", path: 'shellinit.sh'
end
