Vagrant.configure("2") do |config|
  config.vm.box = "cargonauts/boot2docker"

  config.vm.network :private_network, type: 'dhcp'

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false

  # b2d doesn't persist filesystem between reboots
  if config.ssh.respond_to?(:insert_key)
    config.ssh.insert_key = false
  end

  # configure DNS forwarding to Consul
  $configDns = <<CONFIGDNS
HOST_IP=$(ifconfig docker0 | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}')
echo "EXTRA_ARGS='--dns ${HOST_IP-172.17.42.1} --dns 8.8.4.4 --dns 8.8.8.8 --dns-search consul'" > /var/lib/boot2docker/profile
echo "DOCKER_TLS='no'" >> /var/lib/boot2docker/profile
sudo /etc/init.d/docker restart
CONFIGDNS

  config.vm.provision "shell", inline: $configDns
end
