Vagrant.configure("2") do |config|
  # Override docker host with our own
  config.vm.provider "docker" do |d|
    d.force_host_vm       = true
    d.vagrant_vagrantfile = "../docker-host/Vagrantfile"
  end

  config.vm.define "consul" do |consul|
    consul.vm.provider "docker" do |d|
      d.image = "cargonauts/consul-web"
      d.ports = ['53:53/udp', '8500:8500']
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.provider "docker" do |d|
      d.build_dir = "redis-wrapper"
    end
  end

  config.vm.define "helloworld2" do |helloworld|
    helloworld.vm.provider "docker" do |d|
      d.image = "cargonauts/helloworld-python"
      d.cmd = ["/srv/helloworld-db.py"]
      d.ports = ["80:80"]
    end
  end

end
