Vagrant.configure("2") do |config|
  # Override docker host with our own
  config.vm.provider "docker" do |d|
    d.force_host_vm       = true
    d.vagrant_vagrantfile = "../docker-host/Vagrantfile"
  end

  config.vm.define "redis" do |redis|
    redis.vm.provider "docker" do |d|
      d.image = "redis"
    end
  end

  config.vm.define "hellodb" do |hellodb|
    hellodb.vm.provider "docker" do |d|
      d.image = "cargonauts/helloworld-python"
      d.cmd = ["/srv/helloworld-db.py"]
      d.ports = ["80:80"]
    end
  end

end