Vagrant.configure("2") do |config|
  config.vm.box = "cargonauts/boot2docker"

  # Disable vagrant folder sync, because of
  # https://github.com/mitchellh/vagrant/issues/5143
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Show Docker env variables for use with local docker client
  config.vm.provision "shell", path: 'shellinit.sh'
end
